name: Build wheels

on:
    # Trigger on pushes to the mainline branches and version tags. This prevents building commits
    # twice when the pull request source branch is in the same repository.
    #push:
    #    branches:
    #        - main
    #    tags:
    #        - "v*"

    # trigger on pull requests to main
    #pull_request:
    #    branches:
    #        - main

    # trigger on request
    workflow_dispatch:

jobs:
