name: Build and install package

on:
  workflow_dispatch:
  
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          sudo apt-get update && sudo apt-get install python3.10-dev
        
      - name: Build fastddm and install it through pip
        run: pip install .
        
      - name: Check import from the command line
        run: |
          mkdir test-folder && pushd test-folder
          python -c 'import fastddm'
          popd
