name: Build wheels

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # Trigger on request
  workflow_dispatch:

  # Trigger on new published release
  release:
    types:
      - published

  # Trigger on pushes to the mainline branches and version tags. This prevents building commits
  # twice when the pull request source branch is in the same repository.
  #push:
  #    branches:
  #        - main
  #    tags:
  #        - "v*"

  # trigger on pull requests to main
  #pull_request:
  #    branches:
  #        - main

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build SDist
        run: pipx run build --sdist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  check_dist:
    name: Check distributions
    needs: [build_sdist]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          merge-multiple: true
          path: dist

      - name: Check distributions
        run: pipx run twine check --strict dist/*

