name: Check CUDA installation Ubuntu

on:
  workflow_dispatch:
  
jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cuda: ["12.1"]
    
    steps:
      - uses: actions/checkout@v3

      - name: Install CUDA on Ubuntu systems
        if: contains(matrix.os, 'ubuntu')
        env:
          cuda: ${{ matrix.cuda }}
        run: .github/action-scripts/install-cuda-ubuntu.sh
        shell: bash
        
      - name: Check import from the command line
        run: |
          ls /usr/local/cuda*/
