name: Check new CUDA installation Windows

on:
  workflow_dispatch:
  
jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        visual-studio: ["Visual Studio 16 2019"]
        cuda: ["12.1.1"]
    
    steps:
      - uses: Jimver/cuda-toolkit@v0.2.11
        id: cuda-toolkit
        with:
          cuda: '12.1.1'
          sub-packages: '["nvcc", "visual_studio_integration"]'
          non-cuda-sub-packages: '["libcufft"]'

      - name: Check installation and paths
        run: |
          nvcc -V;
          ls $env:CUDA_PATH\bin
          ls $env:CUDA_PATH\include
        shell: powershell
